import json
import textwrap
from pathlib import Path

from app.core.config import settings


def _get_dags_dir() -> Path:
    dags_dir = Path(__file__).resolve().parent.parent.parent.parent / "Apache_Airflow" / "dags"
    dags_dir.mkdir(parents=True, exist_ok=True)
    return dags_dir


def _indent_user_code(code: str, indent: int = 4) -> str:
    """Indent user code properly inside a function body."""
    lines = code.strip().splitlines()
    if not lines:
        return ""
    padded = " " * indent
    return "\n".join(padded + line if line.strip() else "" for line in lines)


def generate_dag(pipeline_id: int, pipeline_name: str, steps: list[dict], max_active_runs: int = 1, on_failure_callback: str = "") -> str:
    dag_id = f"pipeline_{pipeline_id}"
    safe_name = "".join(c if c.isalnum() else "_" for c in pipeline_name)

    step_functions = []
    task_lines = []
    task_ids = []
    var_names = []

    for i, step in enumerate(steps, 1):
        func_name = f"step_{i}"
        var_names.append(func_name)
        raw_task_id = step.get("name", f"Step {i}")
        task_id = "".join(c if c.isalnum() or c == "_" else "_" for c in raw_task_id).strip("_") or f"step_{i}"
        task_ids.append(task_id)
        query_type = step.get("query_type", "sql")
        query = step["query"]
        source_table = step.get("source_table", "")
        dest_table = step.get("dest_table", "")
        execution_timeout = step.get("execution_timeout", 300)
        retries = step.get("retries", 1)
        retry_delay = step.get("retry_delay", 5)

        if query_type == "sql":
            safe_query = json.dumps(query)
            source_comment = f"    # Source: {source_table}\n" if source_table else ""
            dest_comment = f"    # Dest: {dest_table}\n" if dest_table else ""
            body = (
                f"def {func_name}():\n"
                f"{source_comment}{dest_comment}"
                f'    hook = PostgresHook(postgres_conn_id="edupulse")\n'
                f"    conn = hook.get_conn()\n"
                f"    cursor = conn.cursor()\n"
                f"    cursor.execute({safe_query})\n"
                f"    conn.commit()\n"
                f"    cursor.close()\n"
                f"    conn.close()"
            )
        else:
            # Python step — only init hook/engine if source or dest tables exist
            user_code = _indent_user_code(query)
            if source_table or dest_table:
                body = (
                    f"def {func_name}():\n"
                    f'    hook = PostgresHook(postgres_conn_id="edupulse")\n'
                    f"    engine = hook.get_sqlalchemy_engine()\n"
                )
                if source_table:
                    body += f'    df = pd.read_sql("SELECT * FROM {source_table}", engine)\n'
                body += (
                    f"    # --- user transformation ---\n"
                    f"{user_code}\n"
                    f"    # --- end transformation ---\n"
                )
                if dest_table:
                    body += (
                        f'    if not df.empty:\n'
                        f'        df.to_sql("{dest_table}", engine, if_exists="replace", index=False)\n'
                        f'        print(f"Saved {{len(df)}} rows to {dest_table}")\n'
                    )
            else:
                # Pure Python step — no DB connection needed
                body = (
                    f"def {func_name}():\n"
                    f"    # --- user transformation ---\n"
                    f"{user_code}\n"
                    f"    # --- end transformation ---\n"
                )

        step_functions.append(body)
        task_lines.append(
            f'    {func_name} = PythonOperator(\n'
            f'        task_id="{task_id}",\n'
            f'        python_callable={func_name},\n'
            f'        execution_timeout=timedelta(seconds={execution_timeout}),\n'
            f'        retries={retries},\n'
            f'        retry_delay=timedelta(minutes={retry_delay}),\n'
            f'    )'
        )

    task_chain = " >> ".join(var_names)
    functions_block = "\n\n\n".join(step_functions)
    tasks_block = "\n".join(task_lines)

    dag_content = (
        f"# Generated by EduPulse Pipeline Builder\n"
        f"# Pipeline: {pipeline_name} (ID: {pipeline_id})\n"
        f"from datetime import datetime, timedelta\n"
        f"from airflow import DAG\n"
        f"from airflow.operators.python import PythonOperator\n"
        f'from airflow.providers.postgres.hooks.postgres import PostgresHook\n'
        f"import pandas as pd\n\n\n"
        f"{functions_block}\n\n\n"
        f"default_args = {{\n"
        f'    "owner": "edupulse",\n'
        f"    \"depends_on_past\": False,\n"
        f"    \"retries\": 1,\n"
        f"    \"retry_delay\": timedelta(minutes=5),\n"
        f"}}\n\n\n"
        f'with DAG(\n'
        f'    dag_id="{dag_id}",\n'
        f"    default_args=default_args,\n"
        f'    description="Auto-generated: {safe_name}",\n'
        f"    schedule_interval=None,\n"
        f"    start_date=datetime(2026, 1, 1),\n"
        f"    catchup=False,\n"
        f"    max_active_runs={max_active_runs},\n"
        f'    tags=["edupulse", "auto-generated"],\n'
        f") as dag:\n"
        f"{tasks_block}\n\n"
        f"    {task_chain}\n"
    )

    dags_dir = _get_dags_dir()
    dag_file = dags_dir / f"{dag_id}.py"
    dag_file.write_text(dag_content, encoding="utf-8")

    return dag_id


def delete_dag_file(pipeline_id: int) -> bool:
    dag_file = _get_dags_dir() / f"pipeline_{pipeline_id}.py"
    if dag_file.exists():
        dag_file.unlink()
        return True
    return False
